create-links testing characters replaced

diff --git a/create-links b/create-links
--- a/create-links
+++ b/create-links
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Ensure script run with sudo or as root
-if [$(id -u) -ne 0 ]; then
+if [ $(id -u) -ne 0 ]; then
   echo "This script must be run as sudo or as root."
   exit 1
 fi
@@ -21,10 +21,10 @@ if [ -z "$YOUR_HOME" ]; then
 else
  # ssh-add $YOUR_HOME/.ssh/gitlab
   #git clone git@gitlab.com:cit2420/2420-as2-starting-files.git $YOUR_HOME/.dotfilestt || { echo "Error cloning git. Ensure ssh keys are properly configured. Refer to ssh-add and ssh-agent commands.";exit 1; }
-  git clone https://gitlab.com/cit2420/2420-as2-starting-files.git $YOUR_HOME/.dotfilestt
-  ln -sf $YOUR_HOME/.dotfiles/bin $YOUR_HOME/bintt
-  ln -sf $YOUR_HOME/.dotfiles/config $YOUR_HOME/.configtt
-  ln -sf $YOUR_HOME/.dotfiles/home/bashrc $YOUR_HOME/.bashrctt
+  git clone https://gitlab.com/cit2420/2420-as2-starting-files.git $YOUR_HOME/.dotfiles || { echo "Error cloning git. Ensure url is correct and repository is accessible.";exit 1; }
+  ln -sf $YOUR_HOME/.dotfiles/bin $YOUR_HOME/bin
+  ln -sf $YOUR_HOME/.dotfiles/config $YOUR_HOME/.config
+  ln -sf $YOUR_HOME/.dotfiles/home/bashrc $YOUR_HOME/.bashrc
 fi
 
 
