logic to add primary group and to add user

diff --git a/create-user b/create-user
--- a/create-user
+++ b/create-user
@@ -59,6 +59,12 @@ else
   NEW_GID=1000
 fi
 
+# Add primary group for user to /etc/group.
+echo "$USER_NAME:x:$NEW_GID:$USER_NAME" >> /etc/group || echo "Error adding user's primary group to /etc/group. Please check file permissions."
+
+# Add new user to /etc/passwd.
+echo "$USER_NAME:x:$NEW_UID:$NEW_GID::/home/$USER_NAME:$USER_SHELL" >> /etc/passwd || echo "Error adding new user to /etc/passwd. Please check file permissions."
+
 
 
 
